def includeme(config):
    config.add_route("admin_login","/login")
    config.add_route("admin_logout","/logout")
    config.add_route("admin_summary","/summary")
    # Payments and sales
    config.add_route("admin_sales","/sales")
    config.add_route("admin_payments","/sales/payments")
    config.add_route("admin_single_payment","/sales/payments/{ref_code}")
    config.add_route("admin_payment_stage","/sales/payments/{ref_code}/stage/{stage_index}")
    config.add_route("admin_ticket_remove","/sales/payments/{ref_code}/remove/{tick_id}")
    config.add_route("admin_payment_reject","/sales/payments/reject/{ref_code}")
    config.add_route("admin_payment_change","/sales/payments/change/{ref_code}")
    config.add_route("admin_payment_enter", "/sales/payments/enter/{ref_code}")
    config.add_route("admin_sales_export", "/sales/export")
    # Account and group management
    config.add_route("admin_accounts","/accounts")
    config.add_route("admin_accounts_export","/accounts/export")
    config.add_route("admin_users","/accounts/users")
    config.add_route("admin_view_user","/accounts/user/{user_id}")
    config.add_route("admin_user_password", "/accounts/user/{user_id}/password")
    config.add_route("admin_user_add","/accounts/adduser")
    config.add_route("admin_user_add_list", "/accounts/listadditions")
    config.add_route("admin_user_profile_edit","/accounts/user/{user_id}/edit")
    config.add_route("admin_user_delete","/accounts/user/{user_id}/delete")
    config.add_route("admin_user_group","/accounts/users/{user_id}/group")
    config.add_route("admin_group_add", "/accounts/addgroup")
    config.add_route("admin_group_edit", "/accounts/groups/{group_id}/edit")
    config.add_route("admin_group_delete", "/accounts/groups/{group_id}/delete")
    config.add_route("admin_group_filter", "/accounts/groups/{group_id}/filter")
    config.add_route("admin_user_check","/accounts/user/{user_id}/check")
    # Ticket type, release, retract management
    config.add_route("admin_tickets","/tickets")
    config.add_route("admin_ticket_type_add","/tickets/add")
    config.add_route("admin_ticket_type_edit","/tickets/{tick_code}/edit")
    config.add_route("admin_tickets_addons","/tickets/{tick_code}/addons")
    config.add_route("admin_ticket_addon_create","/tickets/{tick_code}/addons/create")
    config.add_route("admin_ticket_addon_edit","/tickets/{tick_code}/addons/{addon_code}/edit")
    config.add_route("admin_ticket_addon_retract","/tickets/{tick_code}/addons/{addon_code}/retract")
    config.add_route("admin_ticket_addon_delete","/tickets/{tick_code}/addons/{addon_code}/delete")
    config.add_route("admin_tickets_type","/tickets/{tick_code}/purchased")
    config.add_route("admin_tickets_all","/tickets/purchased")
    config.add_route("admin_ticket_guest_info","/tickets/ticket/{ticket_id}")
    config.add_route("admin_ticket_guest_info_edit","/tickets/ticket/{ticket_id}/edit")
    config.add_route("admin_ticket_checkin_status","/tickets/ticket/{ticket_id}/checkin")
    config.add_route("admin_tickets_allocate","/tickets/allocate")
    config.add_route("admin_tickets_release","/tickets/{tick_code}/release")
    config.add_route("admin_tickets_retract","/tickets/{tick_code}/retract")
    config.add_route("admin_tickets_delete","/tickets/{tick_code}/delete")
    config.add_route("admin_tickets_report","/tickets/report")
    # Settings views
    config.add_route("admin_settings","/settings")
    config.add_route("admin_payment_settings", "/settings/payment")
    config.add_route("admin_document","/document/{doc_code}")
    config.add_route("admin_notes","/notes/{mode}/{id}")
    config.add_route("admin_queue", "/queue")
    config.add_route("admin_test_email", "/settings/test/email")
    # General views
    config.add_static_view("/static","static",cache_max_age=3600)
    config.add_forbidden_view("ticketing.manage.admin:Admin.forbidden_view", path_info=r"/.*?(admin).*?/")
    config.add_notfound_view("ticketing.manage.admin:Admin.notfound_view", path_info=r"/.*?(admin).*?/")
    # Testing views
    config.include('ticketing.manage.testing', route_prefix="/tests")
    config.add_route("tests_root","/tests")
